name: '🧐 Gemini Pull Request Review'

on:
  pull_request:
    types:
      - 'opened'
      - 'reopened'
  issue_comment:
    types:
      - 'created'
  pull_request_review_comment:
    types:
      - 'created'
  pull_request_review:
    types:
      - 'submitted'
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to review'
        required: true
        type: 'number'

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash'

permissions:
  contents: 'read'
  id-token: 'write'
  issues: 'write'
  pull-requests: 'write'
  statuses: 'write'

jobs:
  pr-review:
    timeout-minutes: 10
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Log author association'
        id: 'log_author'
        env:
          ISSUE_AUTHOR: '${{ github.event.issue.author_association }}'
          COMMENT_AUTHOR: '${{ github.event.comment.author_association }}'
          REVIEW_AUTHOR: '${{ github.event.review.author_association }}'
        run: echo ${AUTHOR}
